### ISSUE TITLE
export default of function should not require a name

### ISSUE THREAD

**Issue by ghost** [Swatinem/rollup-plugin-dts#100]
Steps to reproduce :
Create a new folder and in it execute:
```bash
npm init -y;
npm install --save-dev rollup typescript rollup-plugin-dts;
```
Then create the following files :
```js
// ./rollup.js
import dts from "rollup-plugin-dts";

export default {
	input: "testForBug.d.ts",
	output: [{ file: "./result.d.ts", format: "es" }],
	plugins: [dts()],
};
```
```js
// ./testForBug.d.ts
/**
 * @description @TODO
*/
export default function <T extends object>(object: T, initializationObject: {
    [x in keyof T]: () => Promise<T[x]>;
}): Promise<void>;
```
Then execute :
```bash
npx rollup -c rollup.js;
```
and you will get the following error :
```bash
testForBug.d.ts → ./result.d.ts...
[!] (plugin dts) Error: Could not load /home/lillallol/Desktop/possibleBugRollupDtsPlugin/testForBug.d.ts: FunctionDeclaration should have a name

  2 |  * @description @TODO
  3 | */
> 4 | export default function <T extends object>(object: T, initializationObject: {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 5 |     [x in keyof T]: () => Promise<T[x]>;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 6 | }): Promise<void>;
    | ^^^^^^^^^^^^^^^^^^^
Error: Could not load /home/lillallol/Desktop/possibleBugRollupDtsPlugin/testForBug.d.ts: FunctionDeclaration should have a name

  2 |  * @description @TODO
  3 | */
> 4 | export default function <T extends object>(object: T, initializationObject: {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 5 |     [x in keyof T]: () => Promise<T[x]>;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 6 | }): Promise<void>;
    | ^^^^^^^^^^^^^^^^^^^
    at Transformer.convertFunctionDeclaration (/home/lillallol/Desktop/possibleBugRollupDtsPlugin/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1095:19)
    at Transformer.convertStatement (/home/lillallol/Desktop/possibleBugRollupDtsPlugin/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1031:25)
    at new Transformer (/home/lillallol/Desktop/possibleBugRollupDtsPlugin/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:965:18)
    at transformFile (/home/lillallol/Desktop/possibleBugRollupDtsPlugin/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1277:29)
    at Object.load (/home/lillallol/Desktop/possibleBugRollupDtsPlugin/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1332:33)
    at /home/lillallol/Desktop/possibleBugRollupDtsPlugin/node_modules/rollup/dist/shared/rollup.js:18003:25
```

**Comment by Swatinem** [comment]
I experimented a little bit with this, but its a lot harder to do than expected.  Best bet is to just give your function a name ;-)

**Comment by Swatinem** [comment]
For reference, rollup synthesizes function/class names, as you can see in [this repl example](https://rollupjs.org/repl/?version=2.12.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMGZuJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZmdW5jdGlvbi5qcyU1QyUyMiUzQiU1Q25leHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBjbHMlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmNsYXNzLmpzJTVDJTIyJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZnVuY3Rpb24uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uKCklMjAlN0IlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY2xhc3MuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGNsYXNzJTIwJTdCJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

This is not really compatible with how this plugin works.
