### ISSUE TITLE
Error: end must be greater than start

### ISSUE THREAD

**Issue by josejulio** [Swatinem/rollup-plugin-dts#111]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
interface Stuff {
    id: string;
}
export declare const Stuff: Stuff;
export {};
```

### Error Message

```[!] Error: end must be greater than start
Error: end must be greater than start
    at MagicString.remove (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:979:27)
    at treeshakeNode (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:1569:10)
    at renderStatementList (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:1666:17)
    at Program$1.render (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:8268:13)
    at Module.render (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:10000:18)
    at Chunk$1.preRender (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:11163:39)
    at Bundle$1.prerenderChunks (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:12363:19)
    at Bundle$1.generate (/home/josejulio/Documentos/redhat/insights/insights-common-typescript/node_modules/rollup/dist/shared/rollup.js:12238:18)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I think is related to having the same name for the interface and the constant (discovered as I was trying to have a small reproducer)

**Comment by josejulio** [comment]
Thanks for the fix!
