### ISSUE TITLE
Support keyword export names in namespaces

### ISSUE THREAD

**Issue by angeloashmore** [Swatinem/rollup-plugin-dts#149]
**Note**: This issue occurs when using the plugin on `.ts` files, not `.d.ts` files, so this may be unsupported behavior.

When using JavaScript keywords as exported names in a namespace (e.g. `in`, `class`, `const`), this plugin will throw an "Expected a property assignment" error. The transpiled output converts the keyword into a string (e.g. `{ 'in': in }`).

The plugin seems to expect export names to always be identifiers, which does not include tokens (e.g. strings).

Related PR: #150 

### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
// foo.ts
const _in = 'foo'

export { _in as in }
```

```ts
// index.ts
export * as foo from './foo'
```

Rollup config:

```js
import dts from 'rollup-plugin-dts'

const config = [
  {
    input: './index.ts',
    output: [{ file: 'dist/my-library.d.ts', format: 'es' }],
    plugins: [dts()],
  },
]

export default config
```

### Error Message

```
./index.ts → dist/my-library.d.ts...
[!] (plugin dts) Error: Expected a property assignment

  3 | var foo = /*#__PURE__*/Object.freeze({
  4 |   __proto__: null,
> 5 |   'in': _in
    |   ^^^^^^^^^
  6 | });
  7 |
  8 | export { foo };
Error: Expected a property assignment

  3 | var foo = /*#__PURE__*/Object.freeze({
  4 |   __proto__: null,
> 5 |   'in': _in
    |   ^^^^^^^^^
  6 | });
  7 |
  8 | export { foo };
    at NamespaceFixer.findNamespaces (/[redacted]/rollup-plugin-dts-test/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:152:27)
    at NamespaceFixer.fix (/[redacted]/rollup-plugin-dts-test/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:173:48)
    at Object.renderChunk (/[redacted]/rollup-plugin-dts-test/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1468:27)
    at /[redacted]/rollup-plugin-dts-test/node_modules/rollup/dist/shared/rollup.js:18918:25
```

**Comment by OmgImAlexis** [comment]
@angeloashmore is this the same issue? Just wanted to check before opening my own.

```sh
Error: Expected a property assignment

  3 | var Snoowrap$1 = /*#__PURE__*/Object.freeze({
  4 |   __proto__: null,
> 5 |   get default () { return Snoowrap; }
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  6 | });
  7 |
  8 | declare class Listing<T> extends Array<T> {
    at NamespaceFixer.findNamespaces (/Users/xo/code/OmgImAlexis/snoostream/node_modules/tsup/dist/rollup.js:4942:21)
    at NamespaceFixer.fix (/Users/xo/code/OmgImAlexis/snoostream/node_modules/tsup/dist/rollup.js:4962:48)
    at Object.renderChunk (/Users/xo/code/OmgImAlexis/snoostream/node_modules/tsup/dist/rollup.js:5935:25)
    at /Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:20178:25
```

**Comment by Swatinem** [comment]
It does look similar. Can you provide the original code for that snippet?

**Comment by dimaslanjaka** [comment]
same error on my project.

```log
./tmp/dist/index.d.ts → ./dist/index.d.ts...
[!] (plugin dts) Error: Expected a property assignment

   9 | var __index = /*#__PURE__*/Object.freeze({
  10 |     __proto__: null,
> 11 |     get Application () { return SBG; },
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  12 |     get SBG () { return SBG; },
  13 |     get SitemapOptions () { return SitemapOptions; },
  14 |     get clean () { return index_d$3; },
    at NamespaceFixer.findNamespaces (file:///D:/Repositories/sbg-api/packages/sbg-api/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:315:27)        
    at NamespaceFixer.fix (file:///D:/Repositories/sbg-api/packages/sbg-api/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:336:48)
    at Object.renderChunk (file:///D:/Repositories/sbg-api/packages/sbg-api/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1706:27)
    at D:\Repositories\sbg-api\packages\sbg-api\node_modules\rollup\dist\shared\rollup.js:1087:40
```

here the commit https://github.com/dimaslanjaka/static-blog-generator/commit/404041836bdb1f669137b8166ea592ec972de739
