### ISSUE TITLE
Error in pnpm monorepo

### ISSUE THREAD

**Issue by millsp** [Swatinem/rollup-plugin-dts#154]
We are using your plugin at Prisma to flatten and import external lib definitions. I noticed that it fails when re-exporting objects or functions from another local package. But that only happens when re-exporting from another package from our monorepo. Given the error below, do you have an idea on how to fix this. If not, I could set up a repro? Thanks

### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
const config = [
  {
    input: './runtime-dist/index.d.ts',
    output: [{ file: 'runtime/index.d.ts', format: 'es' }],
    plugins: [
      dts({
        respectExternal: true,
      }),
    ],
  },
  {
    input: './runtime-dist/index-browser.d.ts',
    output: [{ file: 'runtime/index-browser.d.ts', format: 'es' }],
    plugins: [
      dts({
        respectExternal: true,
      }),
    ],
  },
]
```

### Error Message

```
│ ./runtime-dist/index.d.ts → runtime/index.d.ts...
│ (!) Unresolved dependencies
│ https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
│ util (imported by ../../node_modules/.pnpm/sql-template-tag@4.0.0/node_modules/sql-template-tag/dist/in
│ child_process (imported by ../generator-helper/dist/GeneratorProcess.d.ts, ../../node_modules/.pnpm/exe
│ stream (imported by ../../node_modules/.pnpm/execa@5.0.0/node_modules/execa/index.d.ts)
│ [!] TypeError: Cannot destructure property 'column' of 'locate(...)' as it is undefined.
│ TypeError: Cannot destructure property 'column' of 'locate(...)' as it is undefined.
│     at Module.addLocationToLogProps (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node
│     at Module.error (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_modules/rollup/
│     at Module.traceVariable (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_modules
│     at ModuleScope.findVariable (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_mod
│     at FunctionScope.findVariable (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_m
│     at MemberExpression.bind (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_module
│     at AssignmentPattern.bind (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_modul
│     at AssignmentPattern.bind (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_modul
│     at FunctionDeclaration.bind (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_mod
│     at Program.bind (/home/millsp/Work/prisma/src/node_modules/.pnpm/rollup@2.47.0/node_modules/rollup/
│ Error: Command failed with exit code 1: rollup -c
│     at makeError (/home/millsp/Work/prisma/src/node_modules/.pnpm/execa@5.0.0/node_modules/execa/lib/er
│     at handlePromise (/home/millsp/Work/prisma/src/node_modules/.pnpm/execa@5.0.0/node_modules/execa/in
│     at processTicksAndRejections (internal/process/task_queues.js:93:5)
│     at async Promise.all (index 2)
│     at async main (/home/millsp/Work/prisma/src/packages/client/helpers/build.js:38:3) {
│   shortMessage: 'Command failed with exit code 1: rollup -c',
│   command: 'rollup -c',
│   exitCode: 1,
│   signal: undefined,
│   signalDescription: undefined,
│   stdout: undefined,
│   stderr: undefined,
│   failed: true,
│   timedOut: false,
│   isCanceled: false,
│   killed: false
│ }
```

**Comment by Swatinem** [comment]
Hm, a repro would indeed be nice.

You can also set the `DTS_DUMP_AST` env variable in order to have it dump its internal structures. That should give a bit of a hind which file/code it is failing at.

https://github.com/Swatinem/rollup-plugin-dts/blob/a44e6c8ac27b94a03309c5573fbe001b2f5912b0/src/transform/index.ts#L85-L89
