### ISSUE TITLE
`@Entity` (plugin dts) Error: Syntax not yet supported

### ISSUE THREAD

**Issue by khteh** [Swatinem/rollup-plugin-dts#218]
### Checklist

* [ ] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [ ] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

"rollup-plugin-dts": "^4.2.2",
Node: v18.7.0
Typescript: 4.7.4

I declare 2 entities: `Teacher` and `Student`. I am trying to create a one many-to-many relationship table. `Teacher` can have many students registered to it and `Student` can subscribe to more than one teacher.

`EntityBase` class:
```
import { PrimaryGeneratedColumn, Column } from "typeorm"
/*
* Use Data Mapper pattern: https://typeorm.io/active-record-data-mapper
*/
export abstract class EntityBase {
    @PrimaryGeneratedColumn()
    public id: number
    @Column()
    public created: Date
    @Column()
    public modified: Date
}
```
And I would like to create a many-to-many relationships table between `Student` and `Teacher` table. However, when I define the following classes in 2 `.ts` files:
```
import { Entity, Column, ManyToMany, JoinTable } from "typeorm"
import { EntityBase } from "./EntityBase"
import { Teacher } from "./Teacher"
@Entity()
export class Student extends EntityBase {
    @Column()
    public firstName: string

    @Column()
    public lastName: string

    @Column({ unique: true })
    public email: string

    @Column()
    public isSuspended: boolean

    @ManyToMany(() => Teacher, (teacher) => teacher.students)
    @JoinTable()
    public teachers: Teacher[]

    constructor(first: string, last: string, email: string, isSuspended?: boolean) {
        super();
        this.firstName = first;
        this.lastName = last;
        this.email = email;
        this.isSuspended = isSuspended ?? false;
        this.teachers = [];
    }
}
```
```
import { Entity, Column, JoinTable, ManyToMany } from "typeorm"
import { EntityBase } from "./EntityBase"
import { Student } from "./Student"
@Entity()
export class Teacher extends EntityBase {
    @Column()
    public firstName: string

    @Column()
    public lastName: string

    @Column({ unique: true })
    public email: string

    @ManyToMany(() => Student, (student) => student.teachers)
    @JoinTable()
    public students: Student[]

    constructor(first: string, last: string, email: string) {
        super();
        this.firstName = first;
        this.lastName = last;
        this.email = email;
        this.students = [];
    }
}
```
It result in the following error:
```
build/index.d.ts → build/index.d.ts...
[!] (plugin dts) Error: Syntax not yet supported

  2 | import { EntityBase } from "./EntityBase"
  3 | import { Student } from "./Student"
> 4 | declare @Entity()
    | ^^^^^^^
  5 | class Teacher extends EntityBase {
  6 |     @Column()
  7 |     public firstName: string
Domain/Entities/Teacher.ts
Error: Syntax not yet supported

  2 | import { EntityBase } from "./EntityBase"
  3 | import { Student } from "./Student"
> 4 | declare @Entity()
    | ^^^^^^^
  5 | class Teacher extends EntityBase {
  6 |     @Column()
  7 |     public firstName: string
    at Transformer.convertStatement (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1248:19)
    at new Transformer (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1177:18)
    at convert (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1168:25)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1484:31)
    at transformFile (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1588:50)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1601:24)
    at /usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:22840:40

npm ERR! Lifecycle script `rollup` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
```

**Comment by Swatinem** [comment]
The experimental Decorator Syntax is not supported, but I think it should be doable fairly easily.

**Comment by khteh** [comment]
I have switched to [rollup-plugin-ts](https://www.npmjs.com/package/rollup-plugin-ts) for now.
