### ISSUE TITLE
Add hashbang support

### ISSUE THREAD

**Issue by AntoineKM** [Swatinem/rollup-plugin-dts#265]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
// src/cli.ts
import * as yargs from "yargs";
#!/usr/bin/env node
declare const cli: yargs.Argv<{}>;
export default cli;

// code....
```

### Error Message

```sh
DTS Build start
Error: Syntax not yet supported

  1 | import * as yargs from "yargs";
> 2 | #!/usr/bin/env node
    |  ^^^^^^^^^^^^^
  3 | declare const cli: yargs.Argv<{}>;
  4 | export default cli;
  5 |
    at Transformer.convertStatement (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7147:17)
    at new Transformer (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7084:16)
    at convert (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7075:27)
    at Object.transform (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7350:29)
    at Object.writeFile (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7488:55)
    at Object.writeFile (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:18685:14)
    at printSourceFileOrBundle (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:113053:16)
    at emitDeclarationFileOrBundle (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:112985:17)
    at emitSourceFileOrBundle (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:112853:13)
    at forEachEmittedFile (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:112591:34)
Error: error occured in dts build
    at Worker.<anonymous> (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/index.js:2281:26)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
 ELIFECYCLE  Command failed with exit code 1.
ERROR: command finished with error: command (/home/runner/work/dixt/dixt/packages/dixt) pnpm run build exited (1)
```

As mentionned here https://github.com/egoist/tsup/issues/910

**Comment by Swatinem** [comment]
If that is indeed the code snippet, it *is* invalid code, also according to the typescript playground:

https://www.typescriptlang.org/play?ssl=4&ssc=20&pln=3&pc=16#code/JYWwDg9gTgLgBAKjgQwM5wJ7Kgc3QMyghDgCItdVSBuAKAGIBCAegFdUpmAjYAO2YCmvAG5xeEACYDaUgMYAbbALiyIvVPAXAAXJmx4AdAEFcwgDwBvAL4A+OgIAekWHCn5kreZvnBqQA

It is being parsed as:

```
(!(/usr/bin))/env)
```

A negated regexp devided by `env`.

Plus an error:

> '#!' can only be used at the start of a file.

Putting it at the beginning of the file makes it parse-able by TS. Which makes me wonder if the plugin pre-processor might be re-arranging things in an invalid way. On the other hand though, such a hashbang should never occurr in a `.d.ts` file to begin with.

**Comment by AntoineKM** [comment]
So could we exclude the hashbang from these? To avoid this type of error? Because indeed it has nothing to do in a `.d.ts` or if you want I can do it but can you tell me what should be changed?

**Comment by AntoineKM** [comment]
I found a workaround here: https://github.com/AntoineKM/dixt/pull/39/commits/fd56ac9737c76215c82341f7f49c87959eb1fb90
