### ISSUE TITLE
Question: Is it possible to compile TS files via this plugin

### ISSUE THREAD

**Issue by microshine** [Swatinem/rollup-plugin-dts#41]
I'm using your module in some projects. I've updated it from v0.13.0 to v1.1.2 and got an error

```
[!] TypeError: rollupPluginDts.ts is not a function
TypeError: rollupPluginDts.ts is not a function
    at Object.<anonymous> (/Users/microshine/github/pv/asn1-schema/rollup.config.js:15:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.require.extensions..js (/Users/microshine/github/pv/asn1-schema/node_modules/rollup/bin/rollup:1035:24)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at rollup__default.rollup.then.then (/Users/microshine/github/pv/asn1-schema/node_modules/rollup/bin/rollup:1042:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Here is my rollup config file for rollup-plugin-dts@0.13.0

```js
import { ts, dts } from "rollup-plugin-dts";

const pkg = require("./package.json");
const external = [...Object.keys(pkg.dependencies)];
const input = "src/index.ts";

export default [
  { // CommonJS
    input,
    plugins: [
      ts({
        compilerOptions: {
          removeComments: true,
        },
      }),
    ],
    external,
    output: [
      {
        file: pkg.main,
        format: "cjs",
      },
      {
        file: pkg.module,
        format: "es",
      }
    ]
  },
  { // Definitions
    input,
    plugins: [
      dts({
        compilerOptions: {
          noResolve: true,
        }
      }),
    ],
    external,
    output: [
      {
        file: pkg.types,
        format: "es",
      }
    ]
  },
];
```

**Comment by Swatinem** [comment]
I intentionally removed that functionality in v1.
Even though support for `.ts` file input was added back, the recommended usage is with pre-generated `.d.ts` files, for example by using `tsc` with `incremental: true`.
