### ISSUE TITLE
Rollup 1.26.0 regression

### ISSUE THREAD

**Issue by yannickl88** [Swatinem/rollup-plugin-dts#64]
I found that upgrading to rollup 1.26.0 breaks my build using this plugin.

Example:
```typescript
// foo.d.ts
export class A {}
export class B {}
```
```typescript
// index.d.ts
export * from './foo';
```
```js
import dts from 'rollup-plugin-dts';

export default [
    {
        input: './index.d.ts',
        output: {
            file: './out.d.ts',
            format: 'es'
        },
        plugins: [
            dts()
        ]
    }
];
```

Gives the following error:
```
./index.d.ts → ./out.d.ts...
[!] TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at Module.addExport (/example/node_modules/rollup/dist/rollup.js:9971:40)
    at ExportNamedDeclaration.initialise (/example/node_modules/rollup/dist/rollup.js:6783:22)
    at new NodeBase (/example/node_modules/rollup/dist/rollup.js:3110:14)
    at new ExportNamedDeclaration (/example/node_modules/rollup/dist/rollup.js:6773:1)
    at Program$1.parseNode (/example/node_modules/rollup/dist/rollup.js:3230:27)
    at new NodeBase (/example/node_modules/rollup/dist/rollup.js:3109:14)
    at new Program$1 (/example/node_modules/rollup/dist/rollup.js:8190:1)
    at Module.setSource (/example/node_modules/rollup/dist/rollup.js:9904:20)
    at Promise.resolve.catch.then.then.then (/example/node_modules/rollup/dist/rollup.js:12641:20)
```

**Comment by yannickl88** [comment]
Most likely caused by https://github.com/rollup/rollup/pull/3193

**Comment by Swatinem** [comment]
Thanks for the report. I will only be able to look at this next week, as
I'm on vacation right now.

**Comment by yannickl88** [comment]
No problem, I've locked my rollup version to `1.25.2` for now which still works fine.

**Comment by fengwuxp** [comment]
Encountered the same problem, after reducing the version of the rollup (for example: 1.10.x), there is no problem.

**Comment by Swatinem** [comment]
@aleclarson filed this upstream here: https://github.com/rollup/rollup/issues/3210 which seems to fix this issue. I see renovate was also busy bumping to the latest version which is green so I guess I will call this fixed for now, and will look into a proper fix when I catch up with things
