### ISSUE TITLE
Error: end must be greater than start

### ISSUE THREAD

**Issue by bdwain** [Swatinem/rollup-plugin-dts#85]
This was originally opened in #63, but was closed due to not having a failing test case. I have a simple failing test case.

```ts
//index.d.ts
export { foo } from './foo';

//foo.d.ts
export function foo(): {
    bar: (blah: any, hi: any) => void;
};
```

and here is my rollup config

```js
import dts from "rollup-plugin-dts";

const config = [
  {
    input: "./index.d.ts",
    output: [{ file: "./out.d.ts", format: "es" }],
    plugins: [dts()],
  },
];

export default config;
```

then i just run `rollup -c rollup.config.js`

and i get 

```
./index.d.ts → ./out.d.ts...
[!] Error: end must be greater than start
Error: end must be greater than start
    at MagicString.remove (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:7745:27)
    at treeshakeNode (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:8350:10)
    at renderStatementList (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:8441:17)
    at BlockStatement$1.render (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:10923:13)
    at FunctionExpression$1.render (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:8868:23)
    at AssignmentPattern.render (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:11090:20)
    at FunctionDeclaration.render (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:8864:31)
    at renderStatementList (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:8445:25)
    at Program$1.render (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:13055:13)
    at Module.render (/Users/bwain/dev/test/node_modules/rollup/dist/shared/rollup.js:14753:18)
```

**Comment by Swatinem** [comment]
Thanks! With this testcase, it was reasonably easy to fix this.

BTW, the bug was in the way the plugin tried to replace `export function` by `declare function`, because you have to use `declare` inside of `.d.ts` files. ;-)

**Comment by bdwain** [comment]
thanks for doing that so soon!
